### ISSUE TITLE
Max voltage with external 5V regulator

### ISSUE THREAD

**Issue by ehughwilliams** [sim-/tgy#104]
Hi - My first project with brushless and love the Afro 30 and Simon-K code.  Did fine with my first tweaks and re-flash -- thanks!  But now I would like to also use it in a project that runs on a 24V supply (stuck with that, can't change it).

Hobby King lists this controller as 2-4s.  I found a data sheet for the FETs that says they are rated to 30V (or more specifically they have a Drain-source voltage of 30V).  The datasheet for the linear 5V regulator says its absolute max is 26V, but it's a low-drop-out reg that will run happily at 6V input -- so I'd assume that the 4s limit is for the linear 5V regulator's input (to keep it nice and cool)?   If I use an external regulator to produce my 5V, can I just bypass the on-board regulator (unsoldering it if necessary -- very able to do that) and feed my 5V to the BEC pin on the six-pin .1" header (with the UART and I2C connections)?  If that works, does that mean I can _safely_ run up to 30V? (i.e. will the N-FETs handle 24V with a little overhead for spikes?)  Or are there other chips that won't handle it, such as caps that are only 16V, etc? Thanks!

**Comment by sim-** [comment]
Hello! Check the voltage on the capacitor, but the main issue is the Vgs of the FETs. That said, it often works, but it is out of specification. Also, with discrete drive, the other big issue is the current limiting resistors for charging the high side bootstrap capacitors. Again, it may actually just work, but it's going to get a bit hot. The best design is as we originally specified (but which never actually got released because of expense :/) for the afro_hv boards. A dedicated driver to get a good gate voltage and, preferably, buck switching to replace the 7805.

There are some compromises that can work; for example, a 7812 to get a gate voltage (since the current requirements aren't all that high) and then 7805 from that as well (to share the dissipation). I've seen some ZTW board that do this. But these days, it makes more sense to use a proper FET driver, and some of them now have built-in buck regulators.
