### ISSUE TITLE
Which firmware to use with ST20A hobbylord esc

### ISSUE THREAD

**Issue by danvel9** [sim-/tgy#13]
Congratulations for your fantastic work.
I have four of these "ultrapwm escs"  :
http://www.hobbylord.com/en/content/?249.html

and now I'd like to use them with a standard kk2 board.
can you please advice which file to choose?
Thank you in advance.

**Comment by wcbonner** [comment]
@picxels or @craigripper, do you still have the hobbylord ESCs and code to flash them, or did you give up and simply buy ESCs with a higher speed oscilator?

I bought a BumbleBee kit second hand, including the frame, ESCs, and motors. Only after buying it did I find out it was ultraPWM instead of standard PWM. I don't want to deal with finding alternate ESCs that fit in the enclosure if I don't have to.

If I can get a custom HEX without installing the dev environment, I'd appreciate it.

Thanks, Wim.

**Comment by danvel9** [comment]
Yes,  I have 4 of those but I haven't  tried to flash them yet.  I'm not
certain about what code to use.

**Comment by picxels** [comment]
I have the files and I successfully flashed my esc. Ill send them to you
monday when I get to my office.

**Comment by danvel9** [comment]
Thanks!

**Comment by wcbonner** [comment]
I'd love to have a copy of the hex file customized for the hobbylord escs. 

I'd also like input on what I need to do to program the ESCs. 

Do I need to provide power to the ESCs during the programming process beyond the power provided by the USBAsp programming device and cable?

**Comment by danvel9** [comment]
Picxels promised to send it on Monday but haven't received it yet😂.
Anyway,  the power from the programmer is enough for programming.
