### ISSUE TITLE
BRAKE_SPEED = 8 : Constant out of range

### ISSUE THREAD

**Issue by danhouldsworth** [sim-/tgy#59]
Hi Simon,

First - I'm really enjoying using and learning from this code! Superb work!

Here's an issue I've found, and I wanted to check the solution with you.
If we set braking to maximum (ie 8 as suggested in the commentary) then
tgy.asm(line:2657)  ```ldi YL, 1 << BRAKE_SPEED```
returns a warning ```tgy.asm(2657) : Warning : Constant out of range (-128 <= k <= 255). Will be masked```
which makes sense as 1<<8 === 256.
I don't know how AVRA is applying a mask and don't want to risk an undesired setting, so should we update the code to ```ldi YL, (1<<BRAKE_SPEED)-1``` which would then give settings of : 1,3,7,15,31,63,127,255 rather than 2,4,8,16,32,64,256?

Thanks!

**Comment by sim-** [comment]
Missed this, sorry! Actually, the warning is just a nuisance here. I expected it to be 0 and subtract 0, since then the brake strength update divisor is always 0, making it occur at every PWM cycle. I've wrapped it in low() in 0956464 to squelch the warning. Changing it to -1 would have a very different effect, since the minuend is expected to reach 0.
